HYBRID = "hybrid"
SECTION = "section"

section_keywords = {
    "ref-program": [
        "ref",
        "refer",
        "referral",
        "invite",
        "invites",
        "friend",
        "friends",
        "bonus",
        "reward",
        "rewards",
        "earn",
        "commission",
        "affiliate",
        "share",
        "link",
        "invitation",
    ],

    "faq": [
        "what",
        "how",
        "why",
        "question",
        "problem",
        "issue",
        "help",
        "support",
        "faq",
    ],

    "contact": [
        "contact",
        "support",
        "email",
        "telegram",
        "discord",
        "team",
        "manager",
        "human",
        "person",
        "reply",
        "response",
        "reach",
    ],

    "company": [
        "company",
        "about",
        "team",
        "founder",
        "created",
        "owner",
        "who",
        "where",
        "location",
        "country",
        "office",
        "legal",
        "business",
    ],

    "install": [
        "install",
        "download",
        "setup",
        "app",
        "application",
        "ios",
        "android",
        "iphone",
        "mobile",
        "desktop",
        "windows",
        "mac",
        "supported",
        "device",
        "available",
    ],

    "amba-program": [
        "ambassador",
        "amba",
        "community",
        "promote",
        "promotion",
        "campaign",
        "represent",
        "creator",
        "content",
        "social",
        "marketing",
        "influencer",
    ],

    "offer-concierge": [
        "concierge",
        "vip",
        "premium",
        "personal manager",
        "private service",
        "exclusive",
        "high net worth",
        "custom offer",
        "special offer",
        "priority",
        "tailored",
        "personal assistance",
    ],
}